=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MailSafePro::BillingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @api_instance = MailSafePro::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@api_instance).to be_instance_of(MailSafePro::BillingApi)
    end
  end

  # unit tests for change_plan_billing_billing_change_plan_post
  # Change Plan
  # Cambiar el plan del usuario.
  # @param body_change_plan_billing_billing_change_plan_post 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'change_plan_billing_billing_change_plan_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for change_plan_billing_billing_change_plan_post_0
  # Change Plan
  # Cambiar el plan del usuario.
  # @param body_change_plan_billing_billing_change_plan_post 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'change_plan_billing_billing_change_plan_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_checkout_session_billing_billing_create_checkout_session_post
  # Create Checkout Session
  # Crea una checkout session de Stripe para suscripción.
  # @param checkout_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSessionResponse]
  describe 'create_checkout_session_billing_billing_create_checkout_session_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_checkout_session_billing_billing_create_checkout_session_post_0
  # Create Checkout Session
  # Crea una checkout session de Stripe para suscripción.
  # @param checkout_request 
  # @param [Hash] opts the optional parameters
  # @return [CheckoutSessionResponse]
  describe 'create_checkout_session_billing_billing_create_checkout_session_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_subscription_billing_billing_subscription_get
  # Get Subscription
  # Devuelve información de suscripción (plan y próxima fecha de cobro).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [SubscriptionResponse]
  describe 'get_subscription_billing_billing_subscription_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_subscription_billing_billing_subscription_get_0
  # Get Subscription
  # Devuelve información de suscripción (plan y próxima fecha de cobro).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [SubscriptionResponse]
  describe 'get_subscription_billing_billing_subscription_get_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for stripe_webhook_billing_billing_webhook_post
  # Stripe Webhook
  # Webhook de Stripe.
  # @param [Hash] opts the optional parameters
  # @return [WebhookResponse]
  describe 'stripe_webhook_billing_billing_webhook_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for stripe_webhook_billing_billing_webhook_post_0
  # Stripe Webhook
  # Webhook de Stripe.
  # @param [Hash] opts the optional parameters
  # @return [WebhookResponse]
  describe 'stripe_webhook_billing_billing_webhook_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for test_notification_billing_billing_test_notification_post
  # Test Notification
  # Envía un email de prueba de cambio de plan.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>]
  describe 'test_notification_billing_billing_test_notification_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for test_notification_billing_billing_test_notification_post_0
  # Test Notification
  # Envía un email de prueba de cambio de plan.
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>]
  describe 'test_notification_billing_billing_test_notification_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
