=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MailSafePro::JobsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'JobsApi' do
  before do
    # run before each test
    @api_instance = MailSafePro::JobsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JobsApi' do
    it 'should create an instance of JobsApi' do
      expect(@api_instance).to be_instance_of(MailSafePro::JobsApi)
    end
  end

  # unit tests for create_job_jobs_v1_jobs_post
  # Create validation job
  # @param job_create_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_idempotency_key 
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [JobCreateResponse]
  describe 'create_job_jobs_v1_jobs_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_job_jobs_v1_jobs_post_0
  # Create validation job
  # @param job_create_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_idempotency_key 
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [JobCreateResponse]
  describe 'create_job_jobs_v1_jobs_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_job_results_jobs_v1_jobs_job_id_results_get
  # Get job results (paged)
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :size 
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [JobResultsPage]
  describe 'get_job_results_jobs_v1_jobs_job_id_results_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_job_results_jobs_v1_jobs_job_id_results_get_0
  # Get job results (paged)
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [Integer] :size 
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [JobResultsPage]
  describe 'get_job_results_jobs_v1_jobs_job_id_results_get_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_job_status_jobs_v1_jobs_job_id_get
  # Get job status
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [JobStatusResponse]
  describe 'get_job_status_jobs_v1_jobs_job_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_job_status_jobs_v1_jobs_job_id_get_0
  # Get job status
  # @param job_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [JobStatusResponse]
  describe 'get_job_status_jobs_v1_jobs_job_id_get_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
