=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for MailSafePro::WebhooksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WebhooksApi' do
  before do
    # run before each test
    @api_instance = MailSafePro::WebhooksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WebhooksApi' do
    it 'should create an instance of WebhooksApi' do
      expect(@api_instance).to be_instance_of(MailSafePro::WebhooksApi)
    end
  end

  # unit tests for create_webhook_webhooks_management_webhooks_post
  # Create Webhook
  # Create a new webhook endpoint.  Events available: - validation.completed: Single email validation finished - batch.completed: Batch validation finished - usage.limit_reached: API usage limit reached (80%)
  # @param webhook_create 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'create_webhook_webhooks_management_webhooks_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_webhook_webhooks_management_webhooks_webhook_id_delete
  # Delete Webhook
  # Delete webhook.
  # @param webhook_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'delete_webhook_webhooks_management_webhooks_webhook_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_deliveries_webhooks_management_webhooks_webhook_id_deliveries_get
  # Get Deliveries
  # Get delivery history for webhook.
  # @param webhook_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @return [Object]
  describe 'get_deliveries_webhooks_management_webhooks_webhook_id_deliveries_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_webhook_webhooks_management_webhooks_webhook_id_get
  # Get Webhook
  # Get webhook details.
  # @param webhook_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'get_webhook_webhooks_management_webhooks_webhook_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_webhooks_webhooks_management_webhooks_get
  # List Webhooks
  # List all webhooks for authenticated user.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'list_webhooks_webhooks_management_webhooks_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for register_endpoint_webhooks_v1_webhooks_endpoints_register_post
  # Register Endpoint
  # @param register_endpoint 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [Object]
  describe 'register_endpoint_webhooks_v1_webhooks_endpoints_register_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for register_endpoint_webhooks_v1_webhooks_endpoints_register_post_0
  # Register Endpoint
  # @param register_endpoint 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [Object]
  describe 'register_endpoint_webhooks_v1_webhooks_endpoints_register_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_secret_webhooks_v1_webhooks_endpoints_rotate_post
  # Rotate Secret
  # @param rotate_secret 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [Object]
  describe 'rotate_secret_webhooks_v1_webhooks_endpoints_rotate_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_secret_webhooks_v1_webhooks_endpoints_rotate_post_0
  # Rotate Secret
  # @param rotate_secret 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @option opts [String] :authorization 
  # @return [Object]
  describe 'rotate_secret_webhooks_v1_webhooks_endpoints_rotate_post_0 test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for test_webhook_webhooks_management_webhooks_webhook_id_test_post
  # Test Webhook
  # Send test event to webhook.
  # @param webhook_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'test_webhook_webhooks_management_webhooks_webhook_id_test_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_webhook_webhooks_management_webhooks_webhook_id_patch
  # Update Webhook
  # Update webhook configuration.
  # @param webhook_id 
  # @param webhook_update 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'update_webhook_webhooks_management_webhooks_webhook_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
