=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

# Common files
require 'mailsafepro/api_client'
require 'mailsafepro/api_error'
require 'mailsafepro/api_model_base'
require 'mailsafepro/version'
require 'mailsafepro/configuration'

# Models
require 'mailsafepro/models/api_key_create_request'
require 'mailsafepro/models/api_key_list_response'
require 'mailsafepro/models/api_key_meta'
require 'mailsafepro/models/batch_email_response'
require 'mailsafepro/models/batch_validation_request'
require 'mailsafepro/models/body_change_plan_billing_billing_change_plan_post'
require 'mailsafepro/models/checkout_request'
require 'mailsafepro/models/checkout_session_response'
require 'mailsafepro/models/dns_info'
require 'mailsafepro/models/dns_record_dkim'
require 'mailsafepro/models/dns_record_dmarc'
require 'mailsafepro/models/dns_record_spf'
require 'mailsafepro/models/email_response'
require 'mailsafepro/models/email_validation_request'
require 'mailsafepro/models/http_validation_error'
require 'mailsafepro/models/job_create_request'
require 'mailsafepro/models/job_create_response'
require 'mailsafepro/models/job_result_entry'
require 'mailsafepro/models/job_results_page'
require 'mailsafepro/models/job_status_response'
require 'mailsafepro/models/key_rotation_request'
require 'mailsafepro/models/plan_enum'
require 'mailsafepro/models/priority_enum'
require 'mailsafepro/models/register_endpoint'
require 'mailsafepro/models/response_test_notification_billing_billing_test_notification_post_value'
require 'mailsafepro/models/risk_level_enum'
require 'mailsafepro/models/rotate_secret'
require 'mailsafepro/models/smtp_info'
require 'mailsafepro/models/subscription_response'
require 'mailsafepro/models/user_login'
require 'mailsafepro/models/user_register'
require 'mailsafepro/models/validation_error'
require 'mailsafepro/models/validation_error_loc_inner'
require 'mailsafepro/models/webhook_create'
require 'mailsafepro/models/webhook_response'
require 'mailsafepro/models/webhook_update'

# APIs
require 'mailsafepro/api/api_keys_api'
require 'mailsafepro/api/authentication_api'
require 'mailsafepro/api/billing_api'
require 'mailsafepro/api/default_api'
require 'mailsafepro/api/developer_tools_api'
require 'mailsafepro/api/email_validation_api'
require 'mailsafepro/api/health_api'
require 'mailsafepro/api/jobs_api'
require 'mailsafepro/api/logs_api'
require 'mailsafepro/api/validation_api'
require 'mailsafepro/api/webhooks_api'
require 'mailsafepro/api/webhooks_management_api'

module MailSafePro
  class << self
    # Customize default settings for the SDK using block.
    #   MailSafePro.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
