=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'cgi'

module MailSafePro
  class APIKeysApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Create Api Key
    # Create a new API key with atomic transaction. Generates cryptographically secure API keys with proper scoping based on user's current plan. Enforces maximum key limits.
    # @param api_key_create_request [APIKeyCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def create_api_key_api_keys_post(api_key_create_request, opts = {})
      data, _status_code, _headers = create_api_key_api_keys_post_with_http_info(api_key_create_request, opts)
      data
    end

    # Create Api Key
    # Create a new API key with atomic transaction. Generates cryptographically secure API keys with proper scoping based on user&#39;s current plan. Enforces maximum key limits.
    # @param api_key_create_request [APIKeyCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def create_api_key_api_keys_post_with_http_info(api_key_create_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.create_api_key_api_keys_post ...'
      end
      # verify the required parameter 'api_key_create_request' is set
      if @api_client.config.client_side_validation && api_key_create_request.nil?
        fail ArgumentError, "Missing the required parameter 'api_key_create_request' when calling APIKeysApi.create_api_key_api_keys_post"
      end
      # resource path
      local_var_path = '/api-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(api_key_create_request)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.create_api_key_api_keys_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#create_api_key_api_keys_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create Api Key
    # Create a new API key with atomic transaction. Generates cryptographically secure API keys with proper scoping based on user's current plan. Enforces maximum key limits.
    # @param api_key_create_request [APIKeyCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def create_api_key_api_keys_post_0(api_key_create_request, opts = {})
      data, _status_code, _headers = create_api_key_api_keys_post_0_with_http_info(api_key_create_request, opts)
      data
    end

    # Create Api Key
    # Create a new API key with atomic transaction. Generates cryptographically secure API keys with proper scoping based on user&#39;s current plan. Enforces maximum key limits.
    # @param api_key_create_request [APIKeyCreateRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def create_api_key_api_keys_post_0_with_http_info(api_key_create_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.create_api_key_api_keys_post_0 ...'
      end
      # verify the required parameter 'api_key_create_request' is set
      if @api_client.config.client_side_validation && api_key_create_request.nil?
        fail ArgumentError, "Missing the required parameter 'api_key_create_request' when calling APIKeysApi.create_api_key_api_keys_post_0"
      end
      # resource path
      local_var_path = '/api-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(api_key_create_request)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.create_api_key_api_keys_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#create_api_key_api_keys_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Force Sync
    # Force synchronization of user data with rate limiting. Synchronizes API keys with current plan and clears relevant caches. Limited to one sync per 5 minutes per user.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def force_sync_api_keys_force_sync_post(opts = {})
      data, _status_code, _headers = force_sync_api_keys_force_sync_post_with_http_info(opts)
      data
    end

    # Force Sync
    # Force synchronization of user data with rate limiting. Synchronizes API keys with current plan and clears relevant caches. Limited to one sync per 5 minutes per user.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def force_sync_api_keys_force_sync_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.force_sync_api_keys_force_sync_post ...'
      end
      # resource path
      local_var_path = '/api-keys/force-sync'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.force_sync_api_keys_force_sync_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#force_sync_api_keys_force_sync_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Force Sync
    # Force synchronization of user data with rate limiting. Synchronizes API keys with current plan and clears relevant caches. Limited to one sync per 5 minutes per user.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def force_sync_api_keys_force_sync_post_0(opts = {})
      data, _status_code, _headers = force_sync_api_keys_force_sync_post_0_with_http_info(opts)
      data
    end

    # Force Sync
    # Force synchronization of user data with rate limiting. Synchronizes API keys with current plan and clears relevant caches. Limited to one sync per 5 minutes per user.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def force_sync_api_keys_force_sync_post_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.force_sync_api_keys_force_sync_post_0 ...'
      end
      # resource path
      local_var_path = '/api-keys/force-sync'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.force_sync_api_keys_force_sync_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#force_sync_api_keys_force_sync_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Api Key Value
    # Retrieve API key metadata (security-safe). Returns key information without exposing the actual key value. Used for key management and verification purposes.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def get_api_key_value_api_keys_key_hash_value_get(key_hash, opts = {})
      data, _status_code, _headers = get_api_key_value_api_keys_key_hash_value_get_with_http_info(key_hash, opts)
      data
    end

    # Get Api Key Value
    # Retrieve API key metadata (security-safe). Returns key information without exposing the actual key value. Used for key management and verification purposes.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_api_key_value_api_keys_key_hash_value_get_with_http_info(key_hash, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.get_api_key_value_api_keys_key_hash_value_get ...'
      end
      # verify the required parameter 'key_hash' is set
      if @api_client.config.client_side_validation && key_hash.nil?
        fail ArgumentError, "Missing the required parameter 'key_hash' when calling APIKeysApi.get_api_key_value_api_keys_key_hash_value_get"
      end
      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @api_client.config.client_side_validation && key_hash !~ pattern
        fail ArgumentError, "invalid value for 'key_hash' when calling APIKeysApi.get_api_key_value_api_keys_key_hash_value_get, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/api-keys/{key_hash}/value'.sub('{' + 'key_hash' + '}', CGI.escape(key_hash.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.get_api_key_value_api_keys_key_hash_value_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#get_api_key_value_api_keys_key_hash_value_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Api Key Value
    # Retrieve API key metadata (security-safe). Returns key information without exposing the actual key value. Used for key management and verification purposes.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def get_api_key_value_api_keys_key_hash_value_get_0(key_hash, opts = {})
      data, _status_code, _headers = get_api_key_value_api_keys_key_hash_value_get_0_with_http_info(key_hash, opts)
      data
    end

    # Get Api Key Value
    # Retrieve API key metadata (security-safe). Returns key information without exposing the actual key value. Used for key management and verification purposes.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_api_key_value_api_keys_key_hash_value_get_0_with_http_info(key_hash, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.get_api_key_value_api_keys_key_hash_value_get_0 ...'
      end
      # verify the required parameter 'key_hash' is set
      if @api_client.config.client_side_validation && key_hash.nil?
        fail ArgumentError, "Missing the required parameter 'key_hash' when calling APIKeysApi.get_api_key_value_api_keys_key_hash_value_get_0"
      end
      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @api_client.config.client_side_validation && key_hash !~ pattern
        fail ArgumentError, "invalid value for 'key_hash' when calling APIKeysApi.get_api_key_value_api_keys_key_hash_value_get_0, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/api-keys/{key_hash}/value'.sub('{' + 'key_hash' + '}', CGI.escape(key_hash.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.get_api_key_value_api_keys_key_hash_value_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#get_api_key_value_api_keys_key_hash_value_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Usage
    # Get current API usage statistics. Returns usage count, limits, and remaining requests for today. Works with both API keys and JWT tokens.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [Object]
    def get_usage_api_keys_usage_get(opts = {})
      data, _status_code, _headers = get_usage_api_keys_usage_get_with_http_info(opts)
      data
    end

    # Get Usage
    # Get current API usage statistics. Returns usage count, limits, and remaining requests for today. Works with both API keys and JWT tokens.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_usage_api_keys_usage_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.get_usage_api_keys_usage_get ...'
      end
      # resource path
      local_var_path = '/api-keys/usage'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-API-Key'] = opts[:'x_api_key'] if !opts[:'x_api_key'].nil?
      header_params[:'authorization'] = opts[:'authorization'] if !opts[:'authorization'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"APIKeysApi.get_usage_api_keys_usage_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#get_usage_api_keys_usage_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Usage
    # Get current API usage statistics. Returns usage count, limits, and remaining requests for today. Works with both API keys and JWT tokens.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [Object]
    def get_usage_api_keys_usage_get_0(opts = {})
      data, _status_code, _headers = get_usage_api_keys_usage_get_0_with_http_info(opts)
      data
    end

    # Get Usage
    # Get current API usage statistics. Returns usage count, limits, and remaining requests for today. Works with both API keys and JWT tokens.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_usage_api_keys_usage_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.get_usage_api_keys_usage_get_0 ...'
      end
      # resource path
      local_var_path = '/api-keys/usage'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-API-Key'] = opts[:'x_api_key'] if !opts[:'x_api_key'].nil?
      header_params[:'authorization'] = opts[:'authorization'] if !opts[:'authorization'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"APIKeysApi.get_usage_api_keys_usage_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#get_usage_api_keys_usage_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List Api Keys
    # List all API keys for current user with consistent IDs. Returns comprehensive key metadata including status, scopes, and usage information. Handles corrupted key data gracefully.
    # @param [Hash] opts the optional parameters
    # @return [APIKeyListResponse]
    def list_api_keys_api_keys_get(opts = {})
      data, _status_code, _headers = list_api_keys_api_keys_get_with_http_info(opts)
      data
    end

    # List Api Keys
    # List all API keys for current user with consistent IDs. Returns comprehensive key metadata including status, scopes, and usage information. Handles corrupted key data gracefully.
    # @param [Hash] opts the optional parameters
    # @return [Array<(APIKeyListResponse, Integer, Hash)>] APIKeyListResponse data, response status code and response headers
    def list_api_keys_api_keys_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.list_api_keys_api_keys_get ...'
      end
      # resource path
      local_var_path = '/api-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'APIKeyListResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.list_api_keys_api_keys_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#list_api_keys_api_keys_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List Api Keys
    # List all API keys for current user with consistent IDs. Returns comprehensive key metadata including status, scopes, and usage information. Handles corrupted key data gracefully.
    # @param [Hash] opts the optional parameters
    # @return [APIKeyListResponse]
    def list_api_keys_api_keys_get_0(opts = {})
      data, _status_code, _headers = list_api_keys_api_keys_get_0_with_http_info(opts)
      data
    end

    # List Api Keys
    # List all API keys for current user with consistent IDs. Returns comprehensive key metadata including status, scopes, and usage information. Handles corrupted key data gracefully.
    # @param [Hash] opts the optional parameters
    # @return [Array<(APIKeyListResponse, Integer, Hash)>] APIKeyListResponse data, response status code and response headers
    def list_api_keys_api_keys_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.list_api_keys_api_keys_get_0 ...'
      end
      # resource path
      local_var_path = '/api-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'APIKeyListResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.list_api_keys_api_keys_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#list_api_keys_api_keys_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Repair User Data Endpoint
    # Emergency data repair endpoint - ADMINISTRATORS ONLY WARNING: Critical operation; relies on admin scope verification at runtime.
    # @param [Hash] opts the optional parameters
    # @return [Hash<String, String>]
    def repair_user_data_endpoint_api_keys_repair_data_post(opts = {})
      data, _status_code, _headers = repair_user_data_endpoint_api_keys_repair_data_post_with_http_info(opts)
      data
    end

    # Repair User Data Endpoint
    # Emergency data repair endpoint - ADMINISTRATORS ONLY WARNING: Critical operation; relies on admin scope verification at runtime.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Hash<String, String>, Integer, Hash)>] Hash<String, String> data, response status code and response headers
    def repair_user_data_endpoint_api_keys_repair_data_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.repair_user_data_endpoint_api_keys_repair_data_post ...'
      end
      # resource path
      local_var_path = '/api-keys/repair-data'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Hash<String, String>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.repair_user_data_endpoint_api_keys_repair_data_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#repair_user_data_endpoint_api_keys_repair_data_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Repair User Data Endpoint
    # Emergency data repair endpoint - ADMINISTRATORS ONLY WARNING: Critical operation; relies on admin scope verification at runtime.
    # @param [Hash] opts the optional parameters
    # @return [Hash<String, String>]
    def repair_user_data_endpoint_api_keys_repair_data_post_0(opts = {})
      data, _status_code, _headers = repair_user_data_endpoint_api_keys_repair_data_post_0_with_http_info(opts)
      data
    end

    # Repair User Data Endpoint
    # Emergency data repair endpoint - ADMINISTRATORS ONLY WARNING: Critical operation; relies on admin scope verification at runtime.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Hash<String, String>, Integer, Hash)>] Hash<String, String> data, response status code and response headers
    def repair_user_data_endpoint_api_keys_repair_data_post_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.repair_user_data_endpoint_api_keys_repair_data_post_0 ...'
      end
      # resource path
      local_var_path = '/api-keys/repair-data'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Hash<String, String>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.repair_user_data_endpoint_api_keys_repair_data_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#repair_user_data_endpoint_api_keys_repair_data_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Revoke Api Key
    # Revoke an API key with atomic transaction. Immediately invalidates the key and removes it from active sets. Provides audit trail for security compliance.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def revoke_api_key_api_keys_key_hash_revoke_delete(key_hash, opts = {})
      data, _status_code, _headers = revoke_api_key_api_keys_key_hash_revoke_delete_with_http_info(key_hash, opts)
      data
    end

    # Revoke Api Key
    # Revoke an API key with atomic transaction. Immediately invalidates the key and removes it from active sets. Provides audit trail for security compliance.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def revoke_api_key_api_keys_key_hash_revoke_delete_with_http_info(key_hash, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete ...'
      end
      # verify the required parameter 'key_hash' is set
      if @api_client.config.client_side_validation && key_hash.nil?
        fail ArgumentError, "Missing the required parameter 'key_hash' when calling APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete"
      end
      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @api_client.config.client_side_validation && key_hash !~ pattern
        fail ArgumentError, "invalid value for 'key_hash' when calling APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/api-keys/{key_hash}/revoke'.sub('{' + 'key_hash' + '}', CGI.escape(key_hash.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#revoke_api_key_api_keys_key_hash_revoke_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Revoke Api Key
    # Revoke an API key with atomic transaction. Immediately invalidates the key and removes it from active sets. Provides audit trail for security compliance.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def revoke_api_key_api_keys_key_hash_revoke_delete_0(key_hash, opts = {})
      data, _status_code, _headers = revoke_api_key_api_keys_key_hash_revoke_delete_0_with_http_info(key_hash, opts)
      data
    end

    # Revoke Api Key
    # Revoke an API key with atomic transaction. Immediately invalidates the key and removes it from active sets. Provides audit trail for security compliance.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def revoke_api_key_api_keys_key_hash_revoke_delete_0_with_http_info(key_hash, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete_0 ...'
      end
      # verify the required parameter 'key_hash' is set
      if @api_client.config.client_side_validation && key_hash.nil?
        fail ArgumentError, "Missing the required parameter 'key_hash' when calling APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete_0"
      end
      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @api_client.config.client_side_validation && key_hash !~ pattern
        fail ArgumentError, "invalid value for 'key_hash' when calling APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete_0, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/api-keys/{key_hash}/revoke'.sub('{' + 'key_hash' + '}', CGI.escape(key_hash.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.revoke_api_key_api_keys_key_hash_revoke_delete_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#revoke_api_key_api_keys_key_hash_revoke_delete_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Rotate Api Key
    # Rotate API key with grace period. Generates a new key while keeping the old one active for 7 days to allow for smooth transition in client applications.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def rotate_api_key_api_keys_key_hash_rotate_post(key_hash, opts = {})
      data, _status_code, _headers = rotate_api_key_api_keys_key_hash_rotate_post_with_http_info(key_hash, opts)
      data
    end

    # Rotate Api Key
    # Rotate API key with grace period. Generates a new key while keeping the old one active for 7 days to allow for smooth transition in client applications.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def rotate_api_key_api_keys_key_hash_rotate_post_with_http_info(key_hash, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post ...'
      end
      # verify the required parameter 'key_hash' is set
      if @api_client.config.client_side_validation && key_hash.nil?
        fail ArgumentError, "Missing the required parameter 'key_hash' when calling APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post"
      end
      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @api_client.config.client_side_validation && key_hash !~ pattern
        fail ArgumentError, "invalid value for 'key_hash' when calling APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/api-keys/{key_hash}/rotate'.sub('{' + 'key_hash' + '}', CGI.escape(key_hash.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#rotate_api_key_api_keys_key_hash_rotate_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Rotate Api Key
    # Rotate API key with grace period. Generates a new key while keeping the old one active for 7 days to allow for smooth transition in client applications.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def rotate_api_key_api_keys_key_hash_rotate_post_0(key_hash, opts = {})
      data, _status_code, _headers = rotate_api_key_api_keys_key_hash_rotate_post_0_with_http_info(key_hash, opts)
      data
    end

    # Rotate Api Key
    # Rotate API key with grace period. Generates a new key while keeping the old one active for 7 days to allow for smooth transition in client applications.
    # @param key_hash [String] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def rotate_api_key_api_keys_key_hash_rotate_post_0_with_http_info(key_hash, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post_0 ...'
      end
      # verify the required parameter 'key_hash' is set
      if @api_client.config.client_side_validation && key_hash.nil?
        fail ArgumentError, "Missing the required parameter 'key_hash' when calling APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post_0"
      end
      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @api_client.config.client_side_validation && key_hash !~ pattern
        fail ArgumentError, "invalid value for 'key_hash' when calling APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post_0, must conform to the pattern #{pattern}."
      end

      # resource path
      local_var_path = '/api-keys/{key_hash}/rotate'.sub('{' + 'key_hash' + '}', CGI.escape(key_hash.to_s))

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.rotate_api_key_api_keys_key_hash_rotate_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#rotate_api_key_api_keys_key_hash_rotate_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Sync Plan Keys
    # Synchronize current plan with all user API keys. Ensures all existing keys have the correct scopes and permissions based on the user's current subscription plan.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def sync_plan_keys_api_keys_sync_plan_keys_post(opts = {})
      data, _status_code, _headers = sync_plan_keys_api_keys_sync_plan_keys_post_with_http_info(opts)
      data
    end

    # Sync Plan Keys
    # Synchronize current plan with all user API keys. Ensures all existing keys have the correct scopes and permissions based on the user&#39;s current subscription plan.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def sync_plan_keys_api_keys_sync_plan_keys_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.sync_plan_keys_api_keys_sync_plan_keys_post ...'
      end
      # resource path
      local_var_path = '/api-keys/sync-plan-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.sync_plan_keys_api_keys_sync_plan_keys_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#sync_plan_keys_api_keys_sync_plan_keys_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Sync Plan Keys
    # Synchronize current plan with all user API keys. Ensures all existing keys have the correct scopes and permissions based on the user's current subscription plan.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def sync_plan_keys_api_keys_sync_plan_keys_post_0(opts = {})
      data, _status_code, _headers = sync_plan_keys_api_keys_sync_plan_keys_post_0_with_http_info(opts)
      data
    end

    # Sync Plan Keys
    # Synchronize current plan with all user API keys. Ensures all existing keys have the correct scopes and permissions based on the user&#39;s current subscription plan.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def sync_plan_keys_api_keys_sync_plan_keys_post_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: APIKeysApi.sync_plan_keys_api_keys_sync_plan_keys_post_0 ...'
      end
      # resource path
      local_var_path = '/api-keys/sync-plan-keys'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"APIKeysApi.sync_plan_keys_api_keys_sync_plan_keys_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: APIKeysApi#sync_plan_keys_api_keys_sync_plan_keys_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
