=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'cgi'

module MailSafePro
  class AuthenticationApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def auth_health_check_auth_health_auth_get(opts = {})
      data, _status_code, _headers = auth_health_check_auth_health_auth_get_with_http_info(opts)
      data
    end

    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def auth_health_check_auth_health_auth_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.auth_health_check_auth_health_auth_get ...'
      end
      # resource path
      local_var_path = '/auth/health/auth'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.auth_health_check_auth_health_auth_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#auth_health_check_auth_health_auth_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def auth_health_check_auth_health_auth_get_0(opts = {})
      data, _status_code, _headers = auth_health_check_auth_health_auth_get_0_with_http_info(opts)
      data
    end

    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def auth_health_check_auth_health_auth_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.auth_health_check_auth_health_auth_get_0 ...'
      end
      # resource path
      local_var_path = '/auth/health/auth'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.auth_health_check_auth_health_auth_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#auth_health_check_auth_health_auth_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def auth_health_check_auth_health_auth_head(opts = {})
      data, _status_code, _headers = auth_health_check_auth_health_auth_head_with_http_info(opts)
      data
    end

    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def auth_health_check_auth_health_auth_head_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.auth_health_check_auth_health_auth_head ...'
      end
      # resource path
      local_var_path = '/auth/health/auth'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.auth_health_check_auth_health_auth_head",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:HEAD, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#auth_health_check_auth_health_auth_head\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def auth_health_check_auth_health_auth_head_0(opts = {})
      data, _status_code, _headers = auth_health_check_auth_health_auth_head_0_with_http_info(opts)
      data
    end

    # Auth Health Check
    # Health check para autenticación: Redis, JWT y hashing.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def auth_health_check_auth_health_auth_head_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.auth_health_check_auth_health_auth_head_0 ...'
      end
      # resource path
      local_var_path = '/auth/health/auth'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.auth_health_check_auth_health_auth_head_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:HEAD, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#auth_health_check_auth_health_auth_head_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete Account
    # Elimina la cuenta del usuario autenticado y todos sus datos relacionados.  ⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.  Elimina: - Datos del usuario - Todas las API keys - Usage/quota - Suscripciones - Rate limits - Tokens relacionados  Security: - Solo el usuario puede eliminarse a sí mismo (o admin) - Requiere autenticación válida - Registra la acción en logs para auditoría - Rate limited para prevenir abuse
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def delete_account_auth_delete_delete(opts = {})
      data, _status_code, _headers = delete_account_auth_delete_delete_with_http_info(opts)
      data
    end

    # Delete Account
    # Elimina la cuenta del usuario autenticado y todos sus datos relacionados.  ⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.  Elimina: - Datos del usuario - Todas las API keys - Usage/quota - Suscripciones - Rate limits - Tokens relacionados  Security: - Solo el usuario puede eliminarse a sí mismo (o admin) - Requiere autenticación válida - Registra la acción en logs para auditoría - Rate limited para prevenir abuse
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def delete_account_auth_delete_delete_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.delete_account_auth_delete_delete ...'
      end
      # resource path
      local_var_path = '/auth/delete'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"AuthenticationApi.delete_account_auth_delete_delete",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#delete_account_auth_delete_delete\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Delete Account
    # Elimina la cuenta del usuario autenticado y todos sus datos relacionados.  ⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.  Elimina: - Datos del usuario - Todas las API keys - Usage/quota - Suscripciones - Rate limits - Tokens relacionados  Security: - Solo el usuario puede eliminarse a sí mismo (o admin) - Requiere autenticación válida - Registra la acción en logs para auditoría - Rate limited para prevenir abuse
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def delete_account_auth_delete_delete_0(opts = {})
      data, _status_code, _headers = delete_account_auth_delete_delete_0_with_http_info(opts)
      data
    end

    # Delete Account
    # Elimina la cuenta del usuario autenticado y todos sus datos relacionados.  ⚠️ ADVERTENCIA: Esta operación es IRREVERSIBLE.  Elimina: - Datos del usuario - Todas las API keys - Usage/quota - Suscripciones - Rate limits - Tokens relacionados  Security: - Solo el usuario puede eliminarse a sí mismo (o admin) - Requiere autenticación válida - Registra la acción en logs para auditoría - Rate limited para prevenir abuse
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def delete_account_auth_delete_delete_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.delete_account_auth_delete_delete_0 ...'
      end
      # resource path
      local_var_path = '/auth/delete'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"AuthenticationApi.delete_account_auth_delete_delete_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:DELETE, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#delete_account_auth_delete_delete_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Current User
    # Devuelve información básica del usuario actual.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def get_current_user_auth_me_get(opts = {})
      data, _status_code, _headers = get_current_user_auth_me_get_with_http_info(opts)
      data
    end

    # Get Current User
    # Devuelve información básica del usuario actual.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_current_user_auth_me_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.get_current_user_auth_me_get ...'
      end
      # resource path
      local_var_path = '/auth/me'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"AuthenticationApi.get_current_user_auth_me_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#get_current_user_auth_me_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Current User
    # Devuelve información básica del usuario actual.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def get_current_user_auth_me_get_0(opts = {})
      data, _status_code, _headers = get_current_user_auth_me_get_0_with_http_info(opts)
      data
    end

    # Get Current User
    # Devuelve información básica del usuario actual.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def get_current_user_auth_me_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.get_current_user_auth_me_get_0 ...'
      end
      # resource path
      local_var_path = '/auth/me'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"AuthenticationApi.get_current_user_auth_me_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#get_current_user_auth_me_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Login Web User
    # Login de usuario para panel web.  Security features: - Rate limiting por email + IP - Timing attack protection - Generic error messages - PII masking en logs
    # @param user_login [UserLogin] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def login_web_user_auth_login_post(user_login, opts = {})
      data, _status_code, _headers = login_web_user_auth_login_post_with_http_info(user_login, opts)
      data
    end

    # Login Web User
    # Login de usuario para panel web.  Security features: - Rate limiting por email + IP - Timing attack protection - Generic error messages - PII masking en logs
    # @param user_login [UserLogin] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def login_web_user_auth_login_post_with_http_info(user_login, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.login_web_user_auth_login_post ...'
      end
      # verify the required parameter 'user_login' is set
      if @api_client.config.client_side_validation && user_login.nil?
        fail ArgumentError, "Missing the required parameter 'user_login' when calling AuthenticationApi.login_web_user_auth_login_post"
      end
      # resource path
      local_var_path = '/auth/login'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(user_login)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.login_web_user_auth_login_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#login_web_user_auth_login_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Login Web User
    # Login de usuario para panel web.  Security features: - Rate limiting por email + IP - Timing attack protection - Generic error messages - PII masking en logs
    # @param user_login [UserLogin] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def login_web_user_auth_login_post_0(user_login, opts = {})
      data, _status_code, _headers = login_web_user_auth_login_post_0_with_http_info(user_login, opts)
      data
    end

    # Login Web User
    # Login de usuario para panel web.  Security features: - Rate limiting por email + IP - Timing attack protection - Generic error messages - PII masking en logs
    # @param user_login [UserLogin] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def login_web_user_auth_login_post_0_with_http_info(user_login, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.login_web_user_auth_login_post_0 ...'
      end
      # verify the required parameter 'user_login' is set
      if @api_client.config.client_side_validation && user_login.nil?
        fail ArgumentError, "Missing the required parameter 'user_login' when calling AuthenticationApi.login_web_user_auth_login_post_0"
      end
      # resource path
      local_var_path = '/auth/login'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(user_login)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.login_web_user_auth_login_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#login_web_user_auth_login_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Logout
    # Logout idempotente: - Si el access token es válido, lo añade a la blacklist. - Si el access token está expirado, responde 200 indicando que ya estaba expirado. - Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos). - Intenta revocar el refresh token si se proporciona.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def logout_auth_logout_post(opts = {})
      data, _status_code, _headers = logout_auth_logout_post_with_http_info(opts)
      data
    end

    # Logout
    # Logout idempotente: - Si el access token es válido, lo añade a la blacklist. - Si el access token está expirado, responde 200 indicando que ya estaba expirado. - Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos). - Intenta revocar el refresh token si se proporciona.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def logout_auth_logout_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.logout_auth_logout_post ...'
      end
      # resource path
      local_var_path = '/auth/logout'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.logout_auth_logout_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#logout_auth_logout_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Logout
    # Logout idempotente: - Si el access token es válido, lo añade a la blacklist. - Si el access token está expirado, responde 200 indicando que ya estaba expirado. - Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos). - Intenta revocar el refresh token si se proporciona.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def logout_auth_logout_post_0(opts = {})
      data, _status_code, _headers = logout_auth_logout_post_0_with_http_info(opts)
      data
    end

    # Logout
    # Logout idempotente: - Si el access token es válido, lo añade a la blacklist. - Si el access token está expirado, responde 200 indicando que ya estaba expirado. - Solo devuelve 401 si el token es completamente inválido (firma/claims corruptos). - Intenta revocar el refresh token si se proporciona.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def logout_auth_logout_post_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.logout_auth_logout_post_0 ...'
      end
      # resource path
      local_var_path = '/auth/logout'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.logout_auth_logout_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#logout_auth_logout_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Refresh Token
    # Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def refresh_token_auth_refresh_post(opts = {})
      data, _status_code, _headers = refresh_token_auth_refresh_post_with_http_info(opts)
      data
    end

    # Refresh Token
    # Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def refresh_token_auth_refresh_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.refresh_token_auth_refresh_post ...'
      end
      # resource path
      local_var_path = '/auth/refresh'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.refresh_token_auth_refresh_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#refresh_token_auth_refresh_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Refresh Token
    # Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def refresh_token_auth_refresh_post_0(opts = {})
      data, _status_code, _headers = refresh_token_auth_refresh_post_0_with_http_info(opts)
      data
    end

    # Refresh Token
    # Crea un nuevo par de tokens a partir de un refresh token válido y no revocado.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def refresh_token_auth_refresh_post_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.refresh_token_auth_refresh_post_0 ...'
      end
      # resource path
      local_var_path = '/auth/refresh'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.refresh_token_auth_refresh_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#refresh_token_auth_refresh_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Register Web User
    # Registro de usuario para panel web: crea usuario, API key y tokens.
    # @param user_register [UserRegister] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def register_web_user_auth_register_post(user_register, opts = {})
      data, _status_code, _headers = register_web_user_auth_register_post_with_http_info(user_register, opts)
      data
    end

    # Register Web User
    # Registro de usuario para panel web: crea usuario, API key y tokens.
    # @param user_register [UserRegister] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def register_web_user_auth_register_post_with_http_info(user_register, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.register_web_user_auth_register_post ...'
      end
      # verify the required parameter 'user_register' is set
      if @api_client.config.client_side_validation && user_register.nil?
        fail ArgumentError, "Missing the required parameter 'user_register' when calling AuthenticationApi.register_web_user_auth_register_post"
      end
      # resource path
      local_var_path = '/auth/register'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(user_register)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.register_web_user_auth_register_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#register_web_user_auth_register_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Register Web User
    # Registro de usuario para panel web: crea usuario, API key y tokens.
    # @param user_register [UserRegister] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def register_web_user_auth_register_post_0(user_register, opts = {})
      data, _status_code, _headers = register_web_user_auth_register_post_0_with_http_info(user_register, opts)
      data
    end

    # Register Web User
    # Registro de usuario para panel web: crea usuario, API key y tokens.
    # @param user_register [UserRegister] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def register_web_user_auth_register_post_0_with_http_info(user_register, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.register_web_user_auth_register_post_0 ...'
      end
      # verify the required parameter 'user_register' is set
      if @api_client.config.client_side_validation && user_register.nil?
        fail ArgumentError, "Missing the required parameter 'user_register' when calling AuthenticationApi.register_web_user_auth_register_post_0"
      end
      # resource path
      local_var_path = '/auth/register'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(user_register)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"AuthenticationApi.register_web_user_auth_register_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#register_web_user_auth_register_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Rotate Api Key
    # Rotación de API keys con período de gracia; acceso restringido a admin.
    # @param key_rotation_request [KeyRotationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def rotate_api_key_auth_rotate_key_post(key_rotation_request, opts = {})
      data, _status_code, _headers = rotate_api_key_auth_rotate_key_post_with_http_info(key_rotation_request, opts)
      data
    end

    # Rotate Api Key
    # Rotación de API keys con período de gracia; acceso restringido a admin.
    # @param key_rotation_request [KeyRotationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def rotate_api_key_auth_rotate_key_post_with_http_info(key_rotation_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.rotate_api_key_auth_rotate_key_post ...'
      end
      # verify the required parameter 'key_rotation_request' is set
      if @api_client.config.client_side_validation && key_rotation_request.nil?
        fail ArgumentError, "Missing the required parameter 'key_rotation_request' when calling AuthenticationApi.rotate_api_key_auth_rotate_key_post"
      end
      # resource path
      local_var_path = '/auth/rotate-key'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(key_rotation_request)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"AuthenticationApi.rotate_api_key_auth_rotate_key_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#rotate_api_key_auth_rotate_key_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Rotate Api Key
    # Rotación de API keys con período de gracia; acceso restringido a admin.
    # @param key_rotation_request [KeyRotationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def rotate_api_key_auth_rotate_key_post_0(key_rotation_request, opts = {})
      data, _status_code, _headers = rotate_api_key_auth_rotate_key_post_0_with_http_info(key_rotation_request, opts)
      data
    end

    # Rotate Api Key
    # Rotación de API keys con período de gracia; acceso restringido a admin.
    # @param key_rotation_request [KeyRotationRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def rotate_api_key_auth_rotate_key_post_0_with_http_info(key_rotation_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthenticationApi.rotate_api_key_auth_rotate_key_post_0 ...'
      end
      # verify the required parameter 'key_rotation_request' is set
      if @api_client.config.client_side_validation && key_rotation_request.nil?
        fail ArgumentError, "Missing the required parameter 'key_rotation_request' when calling AuthenticationApi.rotate_api_key_auth_rotate_key_post_0"
      end
      # resource path
      local_var_path = '/auth/rotate-key'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(key_rotation_request)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"AuthenticationApi.rotate_api_key_auth_rotate_key_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthenticationApi#rotate_api_key_auth_rotate_key_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
