=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'cgi'

module MailSafePro
  class BillingApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Change Plan
    # Cambiar el plan del usuario.
    # @param body_change_plan_billing_billing_change_plan_post [BodyChangePlanBillingBillingChangePlanPost] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def change_plan_billing_billing_change_plan_post(body_change_plan_billing_billing_change_plan_post, opts = {})
      data, _status_code, _headers = change_plan_billing_billing_change_plan_post_with_http_info(body_change_plan_billing_billing_change_plan_post, opts)
      data
    end

    # Change Plan
    # Cambiar el plan del usuario.
    # @param body_change_plan_billing_billing_change_plan_post [BodyChangePlanBillingBillingChangePlanPost] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def change_plan_billing_billing_change_plan_post_with_http_info(body_change_plan_billing_billing_change_plan_post, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.change_plan_billing_billing_change_plan_post ...'
      end
      # verify the required parameter 'body_change_plan_billing_billing_change_plan_post' is set
      if @api_client.config.client_side_validation && body_change_plan_billing_billing_change_plan_post.nil?
        fail ArgumentError, "Missing the required parameter 'body_change_plan_billing_billing_change_plan_post' when calling BillingApi.change_plan_billing_billing_change_plan_post"
      end
      # resource path
      local_var_path = '/billing/billing/change-plan'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body_change_plan_billing_billing_change_plan_post)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"BillingApi.change_plan_billing_billing_change_plan_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#change_plan_billing_billing_change_plan_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Change Plan
    # Cambiar el plan del usuario.
    # @param body_change_plan_billing_billing_change_plan_post [BodyChangePlanBillingBillingChangePlanPost] 
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def change_plan_billing_billing_change_plan_post_0(body_change_plan_billing_billing_change_plan_post, opts = {})
      data, _status_code, _headers = change_plan_billing_billing_change_plan_post_0_with_http_info(body_change_plan_billing_billing_change_plan_post, opts)
      data
    end

    # Change Plan
    # Cambiar el plan del usuario.
    # @param body_change_plan_billing_billing_change_plan_post [BodyChangePlanBillingBillingChangePlanPost] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def change_plan_billing_billing_change_plan_post_0_with_http_info(body_change_plan_billing_billing_change_plan_post, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.change_plan_billing_billing_change_plan_post_0 ...'
      end
      # verify the required parameter 'body_change_plan_billing_billing_change_plan_post' is set
      if @api_client.config.client_side_validation && body_change_plan_billing_billing_change_plan_post.nil?
        fail ArgumentError, "Missing the required parameter 'body_change_plan_billing_billing_change_plan_post' when calling BillingApi.change_plan_billing_billing_change_plan_post_0"
      end
      # resource path
      local_var_path = '/billing/billing/change-plan'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(body_change_plan_billing_billing_change_plan_post)

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"BillingApi.change_plan_billing_billing_change_plan_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#change_plan_billing_billing_change_plan_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create Checkout Session
    # Crea una checkout session de Stripe para suscripción.
    # @param checkout_request [CheckoutRequest] 
    # @param [Hash] opts the optional parameters
    # @return [CheckoutSessionResponse]
    def create_checkout_session_billing_billing_create_checkout_session_post(checkout_request, opts = {})
      data, _status_code, _headers = create_checkout_session_billing_billing_create_checkout_session_post_with_http_info(checkout_request, opts)
      data
    end

    # Create Checkout Session
    # Crea una checkout session de Stripe para suscripción.
    # @param checkout_request [CheckoutRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(CheckoutSessionResponse, Integer, Hash)>] CheckoutSessionResponse data, response status code and response headers
    def create_checkout_session_billing_billing_create_checkout_session_post_with_http_info(checkout_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.create_checkout_session_billing_billing_create_checkout_session_post ...'
      end
      # verify the required parameter 'checkout_request' is set
      if @api_client.config.client_side_validation && checkout_request.nil?
        fail ArgumentError, "Missing the required parameter 'checkout_request' when calling BillingApi.create_checkout_session_billing_billing_create_checkout_session_post"
      end
      # resource path
      local_var_path = '/billing/billing/create-checkout-session'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(checkout_request)

      # return_type
      return_type = opts[:debug_return_type] || 'CheckoutSessionResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"BillingApi.create_checkout_session_billing_billing_create_checkout_session_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#create_checkout_session_billing_billing_create_checkout_session_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Create Checkout Session
    # Crea una checkout session de Stripe para suscripción.
    # @param checkout_request [CheckoutRequest] 
    # @param [Hash] opts the optional parameters
    # @return [CheckoutSessionResponse]
    def create_checkout_session_billing_billing_create_checkout_session_post_0(checkout_request, opts = {})
      data, _status_code, _headers = create_checkout_session_billing_billing_create_checkout_session_post_0_with_http_info(checkout_request, opts)
      data
    end

    # Create Checkout Session
    # Crea una checkout session de Stripe para suscripción.
    # @param checkout_request [CheckoutRequest] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(CheckoutSessionResponse, Integer, Hash)>] CheckoutSessionResponse data, response status code and response headers
    def create_checkout_session_billing_billing_create_checkout_session_post_0_with_http_info(checkout_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.create_checkout_session_billing_billing_create_checkout_session_post_0 ...'
      end
      # verify the required parameter 'checkout_request' is set
      if @api_client.config.client_side_validation && checkout_request.nil?
        fail ArgumentError, "Missing the required parameter 'checkout_request' when calling BillingApi.create_checkout_session_billing_billing_create_checkout_session_post_0"
      end
      # resource path
      local_var_path = '/billing/billing/create-checkout-session'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(checkout_request)

      # return_type
      return_type = opts[:debug_return_type] || 'CheckoutSessionResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"BillingApi.create_checkout_session_billing_billing_create_checkout_session_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#create_checkout_session_billing_billing_create_checkout_session_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Subscription
    # Devuelve información de suscripción (plan y próxima fecha de cobro).
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [SubscriptionResponse]
    def get_subscription_billing_billing_subscription_get(opts = {})
      data, _status_code, _headers = get_subscription_billing_billing_subscription_get_with_http_info(opts)
      data
    end

    # Get Subscription
    # Devuelve información de suscripción (plan y próxima fecha de cobro).
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [Array<(SubscriptionResponse, Integer, Hash)>] SubscriptionResponse data, response status code and response headers
    def get_subscription_billing_billing_subscription_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.get_subscription_billing_billing_subscription_get ...'
      end
      # resource path
      local_var_path = '/billing/billing/subscription'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-API-Key'] = opts[:'x_api_key'] if !opts[:'x_api_key'].nil?
      header_params[:'authorization'] = opts[:'authorization'] if !opts[:'authorization'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SubscriptionResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"BillingApi.get_subscription_billing_billing_subscription_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#get_subscription_billing_billing_subscription_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Get Subscription
    # Devuelve información de suscripción (plan y próxima fecha de cobro).
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [SubscriptionResponse]
    def get_subscription_billing_billing_subscription_get_0(opts = {})
      data, _status_code, _headers = get_subscription_billing_billing_subscription_get_0_with_http_info(opts)
      data
    end

    # Get Subscription
    # Devuelve información de suscripción (plan y próxima fecha de cobro).
    # @param [Hash] opts the optional parameters
    # @option opts [String] :x_api_key 
    # @option opts [String] :authorization 
    # @return [Array<(SubscriptionResponse, Integer, Hash)>] SubscriptionResponse data, response status code and response headers
    def get_subscription_billing_billing_subscription_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.get_subscription_billing_billing_subscription_get_0 ...'
      end
      # resource path
      local_var_path = '/billing/billing/subscription'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      header_params[:'X-API-Key'] = opts[:'x_api_key'] if !opts[:'x_api_key'].nil?
      header_params[:'authorization'] = opts[:'authorization'] if !opts[:'authorization'].nil?

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'SubscriptionResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"BillingApi.get_subscription_billing_billing_subscription_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#get_subscription_billing_billing_subscription_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Stripe Webhook
    # Webhook de Stripe.
    # @param [Hash] opts the optional parameters
    # @return [WebhookResponse]
    def stripe_webhook_billing_billing_webhook_post(opts = {})
      data, _status_code, _headers = stripe_webhook_billing_billing_webhook_post_with_http_info(opts)
      data
    end

    # Stripe Webhook
    # Webhook de Stripe.
    # @param [Hash] opts the optional parameters
    # @return [Array<(WebhookResponse, Integer, Hash)>] WebhookResponse data, response status code and response headers
    def stripe_webhook_billing_billing_webhook_post_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.stripe_webhook_billing_billing_webhook_post ...'
      end
      # resource path
      local_var_path = '/billing/billing/webhook'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'WebhookResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"BillingApi.stripe_webhook_billing_billing_webhook_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#stripe_webhook_billing_billing_webhook_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Stripe Webhook
    # Webhook de Stripe.
    # @param [Hash] opts the optional parameters
    # @return [WebhookResponse]
    def stripe_webhook_billing_billing_webhook_post_0(opts = {})
      data, _status_code, _headers = stripe_webhook_billing_billing_webhook_post_0_with_http_info(opts)
      data
    end

    # Stripe Webhook
    # Webhook de Stripe.
    # @param [Hash] opts the optional parameters
    # @return [Array<(WebhookResponse, Integer, Hash)>] WebhookResponse data, response status code and response headers
    def stripe_webhook_billing_billing_webhook_post_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.stripe_webhook_billing_billing_webhook_post_0 ...'
      end
      # resource path
      local_var_path = '/billing/billing/webhook'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'WebhookResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"BillingApi.stripe_webhook_billing_billing_webhook_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#stripe_webhook_billing_billing_webhook_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Test Notification
    # Envía un email de prueba de cambio de plan.
    # @param request_body [Hash<String, String>] 
    # @param [Hash] opts the optional parameters
    # @return [Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>]
    def test_notification_billing_billing_test_notification_post(request_body, opts = {})
      data, _status_code, _headers = test_notification_billing_billing_test_notification_post_with_http_info(request_body, opts)
      data
    end

    # Test Notification
    # Envía un email de prueba de cambio de plan.
    # @param request_body [Hash<String, String>] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>, Integer, Hash)>] Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue> data, response status code and response headers
    def test_notification_billing_billing_test_notification_post_with_http_info(request_body, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.test_notification_billing_billing_test_notification_post ...'
      end
      # verify the required parameter 'request_body' is set
      if @api_client.config.client_side_validation && request_body.nil?
        fail ArgumentError, "Missing the required parameter 'request_body' when calling BillingApi.test_notification_billing_billing_test_notification_post"
      end
      # resource path
      local_var_path = '/billing/billing/test-notification'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(request_body)

      # return_type
      return_type = opts[:debug_return_type] || 'Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"BillingApi.test_notification_billing_billing_test_notification_post",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#test_notification_billing_billing_test_notification_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Test Notification
    # Envía un email de prueba de cambio de plan.
    # @param request_body [Hash<String, String>] 
    # @param [Hash] opts the optional parameters
    # @return [Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>]
    def test_notification_billing_billing_test_notification_post_0(request_body, opts = {})
      data, _status_code, _headers = test_notification_billing_billing_test_notification_post_0_with_http_info(request_body, opts)
      data
    end

    # Test Notification
    # Envía un email de prueba de cambio de plan.
    # @param request_body [Hash<String, String>] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>, Integer, Hash)>] Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue> data, response status code and response headers
    def test_notification_billing_billing_test_notification_post_0_with_http_info(request_body, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: BillingApi.test_notification_billing_billing_test_notification_post_0 ...'
      end
      # verify the required parameter 'request_body' is set
      if @api_client.config.client_side_validation && request_body.nil?
        fail ArgumentError, "Missing the required parameter 'request_body' when calling BillingApi.test_notification_billing_billing_test_notification_post_0"
      end
      # resource path
      local_var_path = '/billing/billing/test-notification'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(request_body)

      # return_type
      return_type = opts[:debug_return_type] || 'Hash<String, ResponseTestNotificationBillingBillingTestNotificationPostValue>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"BillingApi.test_notification_billing_billing_test_notification_post_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: BillingApi#test_notification_billing_billing_test_notification_post_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
