=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'cgi'

module MailSafePro
  class HealthApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Basic health check
    # Basic health check for load balancers.  Returns 200 if service is running. Fast response, no dependency checks.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def basic_health_health_get(opts = {})
      data, _status_code, _headers = basic_health_health_get_with_http_info(opts)
      data
    end

    # Basic health check
    # Basic health check for load balancers.  Returns 200 if service is running. Fast response, no dependency checks.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def basic_health_health_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.basic_health_health_get ...'
      end
      # resource path
      local_var_path = '/health'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.basic_health_health_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#basic_health_health_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Basic health check
    # Basic health check for load balancers.  Returns 200 if service is running. Fast response, no dependency checks.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def basic_health_health_get_0(opts = {})
      data, _status_code, _headers = basic_health_health_get_0_with_http_info(opts)
      data
    end

    # Basic health check
    # Basic health check for load balancers.  Returns 200 if service is running. Fast response, no dependency checks.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def basic_health_health_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.basic_health_health_get_0 ...'
      end
      # resource path
      local_var_path = '/health'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.basic_health_health_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#basic_health_health_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Circuit Breaker Status
    # ✅ Circuit breaker status for all services. Shows state of Redis, SMTP, DNS, and other circuit breakers.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def circuit_breaker_status_admin_circuit_breaker_status_get(opts = {})
      data, _status_code, _headers = circuit_breaker_status_admin_circuit_breaker_status_get_with_http_info(opts)
      data
    end

    # Circuit Breaker Status
    # ✅ Circuit breaker status for all services. Shows state of Redis, SMTP, DNS, and other circuit breakers.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def circuit_breaker_status_admin_circuit_breaker_status_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.circuit_breaker_status_admin_circuit_breaker_status_get ...'
      end
      # resource path
      local_var_path = '/admin/circuit-breaker-status'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.circuit_breaker_status_admin_circuit_breaker_status_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#circuit_breaker_status_admin_circuit_breaker_status_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Detailed health check
    # Detailed health check with all component statuses.  Returns comprehensive health information for monitoring.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def detailed_health_health_detailed_get(opts = {})
      data, _status_code, _headers = detailed_health_health_detailed_get_with_http_info(opts)
      data
    end

    # Detailed health check
    # Detailed health check with all component statuses.  Returns comprehensive health information for monitoring.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def detailed_health_health_detailed_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.detailed_health_health_detailed_get ...'
      end
      # resource path
      local_var_path = '/health/detailed'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.detailed_health_health_detailed_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#detailed_health_health_detailed_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Detailed health check
    # Detailed health check with all component statuses.  Returns comprehensive health information for monitoring.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def detailed_health_health_detailed_get_0(opts = {})
      data, _status_code, _headers = detailed_health_health_detailed_get_0_with_http_info(opts)
      data
    end

    # Detailed health check
    # Detailed health check with all component statuses.  Returns comprehensive health information for monitoring.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def detailed_health_health_detailed_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.detailed_health_health_detailed_get_0 ...'
      end
      # resource path
      local_var_path = '/health/detailed'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.detailed_health_health_detailed_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#detailed_health_health_detailed_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Healthcheck
    # Basic health check endpoint (backward compatibility)
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def healthcheck_healthcheck_get(opts = {})
      data, _status_code, _headers = healthcheck_healthcheck_get_with_http_info(opts)
      data
    end

    # Healthcheck
    # Basic health check endpoint (backward compatibility)
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def healthcheck_healthcheck_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.healthcheck_healthcheck_get ...'
      end
      # resource path
      local_var_path = '/healthcheck'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.healthcheck_healthcheck_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#healthcheck_healthcheck_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Healthcheck
    # Basic health check endpoint (backward compatibility)
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def healthcheck_healthcheck_head(opts = {})
      data, _status_code, _headers = healthcheck_healthcheck_head_with_http_info(opts)
      data
    end

    # Healthcheck
    # Basic health check endpoint (backward compatibility)
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def healthcheck_healthcheck_head_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.healthcheck_healthcheck_head ...'
      end
      # resource path
      local_var_path = '/healthcheck'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.healthcheck_healthcheck_head",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:HEAD, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#healthcheck_healthcheck_head\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Liveness Check
    # ✅ MEJORA: Kubernetes liveness probe  Returns 200 if the application is alive (not deadlocked) Used by Kubernetes to restart the pod if unhealthy
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def liveness_check_health_liveness_get(opts = {})
      data, _status_code, _headers = liveness_check_health_liveness_get_with_http_info(opts)
      data
    end

    # Liveness Check
    # ✅ MEJORA: Kubernetes liveness probe  Returns 200 if the application is alive (not deadlocked) Used by Kubernetes to restart the pod if unhealthy
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def liveness_check_health_liveness_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.liveness_check_health_liveness_get ...'
      end
      # resource path
      local_var_path = '/health/liveness'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.liveness_check_health_liveness_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#liveness_check_health_liveness_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Liveness probe (Kubernetes)
    # Kubernetes liveness probe.  Returns 200 if the application is running. Should restart pod if this fails.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def liveness_health_live_get(opts = {})
      data, _status_code, _headers = liveness_health_live_get_with_http_info(opts)
      data
    end

    # Liveness probe (Kubernetes)
    # Kubernetes liveness probe.  Returns 200 if the application is running. Should restart pod if this fails.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def liveness_health_live_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.liveness_health_live_get ...'
      end
      # resource path
      local_var_path = '/health/live'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.liveness_health_live_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#liveness_health_live_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Liveness probe (Kubernetes)
    # Kubernetes liveness probe.  Returns 200 if the application is running. Should restart pod if this fails.
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def liveness_health_live_get_0(opts = {})
      data, _status_code, _headers = liveness_health_live_get_0_with_http_info(opts)
      data
    end

    # Liveness probe (Kubernetes)
    # Kubernetes liveness probe.  Returns 200 if the application is running. Should restart pod if this fails.
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def liveness_health_live_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.liveness_health_live_get_0 ...'
      end
      # resource path
      local_var_path = '/health/live'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.liveness_health_live_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#liveness_health_live_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Readiness Check
    # ✅ MEJORA: Kubernetes readiness probe  Returns 200 if the application is ready to serve traffic Checks all critical dependencies (PostgreSQL, Redis, ARQ)
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def readiness_check_health_readiness_get(opts = {})
      data, _status_code, _headers = readiness_check_health_readiness_get_with_http_info(opts)
      data
    end

    # Readiness Check
    # ✅ MEJORA: Kubernetes readiness probe  Returns 200 if the application is ready to serve traffic Checks all critical dependencies (PostgreSQL, Redis, ARQ)
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def readiness_check_health_readiness_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.readiness_check_health_readiness_get ...'
      end
      # resource path
      local_var_path = '/health/readiness'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.readiness_check_health_readiness_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#readiness_check_health_readiness_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Readiness probe (Kubernetes)
    # Kubernetes readiness probe.  Returns 200 if service is ready to accept traffic. Checks critical dependencies (Redis).
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def readiness_health_ready_get(opts = {})
      data, _status_code, _headers = readiness_health_ready_get_with_http_info(opts)
      data
    end

    # Readiness probe (Kubernetes)
    # Kubernetes readiness probe.  Returns 200 if service is ready to accept traffic. Checks critical dependencies (Redis).
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def readiness_health_ready_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.readiness_health_ready_get ...'
      end
      # resource path
      local_var_path = '/health/ready'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.readiness_health_ready_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#readiness_health_ready_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Readiness probe (Kubernetes)
    # Kubernetes readiness probe.  Returns 200 if service is ready to accept traffic. Checks critical dependencies (Redis).
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def readiness_health_ready_get_0(opts = {})
      data, _status_code, _headers = readiness_health_ready_get_0_with_http_info(opts)
      data
    end

    # Readiness probe (Kubernetes)
    # Kubernetes readiness probe.  Returns 200 if service is ready to accept traffic. Checks critical dependencies (Redis).
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def readiness_health_ready_get_0_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.readiness_health_ready_get_0 ...'
      end
      # resource path
      local_var_path = '/health/ready'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.readiness_health_ready_get_0",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#readiness_health_ready_get_0\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Service Status
    # ✅ MEJORA: Detailed service status with feature flags  Shows which features are available and which are running in degraded mode
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def service_status_status_get(opts = {})
      data, _status_code, _headers = service_status_status_get_with_http_info(opts)
      data
    end

    # Service Status
    # ✅ MEJORA: Detailed service status with feature flags  Shows which features are available and which are running in degraded mode
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def service_status_status_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.service_status_status_get ...'
      end
      # resource path
      local_var_path = '/status'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.service_status_status_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#service_status_status_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Startup Check
    # ✅ MEJORA: Kubernetes startup probe  Returns 200 once the application has completed startup Used to delay readiness checks until startup is complete
    # @param [Hash] opts the optional parameters
    # @return [Object]
    def startup_check_health_startup_get(opts = {})
      data, _status_code, _headers = startup_check_health_startup_get_with_http_info(opts)
      data
    end

    # Startup Check
    # ✅ MEJORA: Kubernetes startup probe  Returns 200 once the application has completed startup Used to delay readiness checks until startup is complete
    # @param [Hash] opts the optional parameters
    # @return [Array<(Object, Integer, Hash)>] Object data, response status code and response headers
    def startup_check_health_startup_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: HealthApi.startup_check_health_startup_get ...'
      end
      # resource path
      local_var_path = '/health/startup'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Object'

      # auth_names
      auth_names = opts[:debug_auth_names] || []

      new_options = opts.merge(
        :operation => :"HealthApi.startup_check_health_startup_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: HealthApi#startup_check_health_startup_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
