=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module MailSafePro
  # API Key list response
  class APIKeyListResponse < ApiModelBase
    # List of API keys
    attr_accessor :keys

    # Total number of keys
    attr_accessor :total_count

    # Number of active keys
    attr_accessor :active_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'keys' => :'keys',
        :'total_count' => :'total_count',
        :'active_count' => :'active_count'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'keys' => :'Array<APIKeyMeta>',
        :'total_count' => :'Integer',
        :'active_count' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSafePro::APIKeyListResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSafePro::APIKeyListResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'keys')
        if (value = attributes[:'keys']).is_a?(Array)
          self.keys = value
        end
      else
        self.keys = nil
      end

      if attributes.key?(:'total_count')
        self.total_count = attributes[:'total_count']
      else
        self.total_count = nil
      end

      if attributes.key?(:'active_count')
        self.active_count = attributes[:'active_count']
      else
        self.active_count = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @keys.nil?
        invalid_properties.push('invalid value for "keys", keys cannot be nil.')
      end

      if @total_count.nil?
        invalid_properties.push('invalid value for "total_count", total_count cannot be nil.')
      end

      if @total_count < 0
        invalid_properties.push('invalid value for "total_count", must be greater than or equal to 0.')
      end

      if @active_count.nil?
        invalid_properties.push('invalid value for "active_count", active_count cannot be nil.')
      end

      if @active_count < 0
        invalid_properties.push('invalid value for "active_count", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @keys.nil?
      return false if @total_count.nil?
      return false if @total_count < 0
      return false if @active_count.nil?
      return false if @active_count < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] keys Value to be assigned
    def keys=(keys)
      if keys.nil?
        fail ArgumentError, 'keys cannot be nil'
      end

      @keys = keys
    end

    # Custom attribute writer method with validation
    # @param [Object] total_count Value to be assigned
    def total_count=(total_count)
      if total_count.nil?
        fail ArgumentError, 'total_count cannot be nil'
      end

      if total_count < 0
        fail ArgumentError, 'invalid value for "total_count", must be greater than or equal to 0.'
      end

      @total_count = total_count
    end

    # Custom attribute writer method with validation
    # @param [Object] active_count Value to be assigned
    def active_count=(active_count)
      if active_count.nil?
        fail ArgumentError, 'active_count cannot be nil'
      end

      if active_count < 0
        fail ArgumentError, 'invalid value for "active_count", must be greater than or equal to 0.'
      end

      @active_count = active_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          keys == o.keys &&
          total_count == o.total_count &&
          active_count == o.active_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [keys, total_count, active_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
