=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module MailSafePro
  # Request model for batch email validation
  class BatchValidationRequest < ApiModelBase
    # List of email addresses to validate (can include invalid formats)
    attr_accessor :emails

    # Perform SMTP verification for all emails
    attr_accessor :check_smtp

    # Include raw DNS records in responses
    attr_accessor :include_raw_dns

    # Number of emails to process in each batch
    attr_accessor :batch_size

    # Maximum concurrent validation requests
    attr_accessor :concurrent_requests

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'emails' => :'emails',
        :'check_smtp' => :'check_smtp',
        :'include_raw_dns' => :'include_raw_dns',
        :'batch_size' => :'batch_size',
        :'concurrent_requests' => :'concurrent_requests'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'emails' => :'Array<String>',
        :'check_smtp' => :'Boolean',
        :'include_raw_dns' => :'Boolean',
        :'batch_size' => :'Integer',
        :'concurrent_requests' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSafePro::BatchValidationRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSafePro::BatchValidationRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'emails')
        if (value = attributes[:'emails']).is_a?(Array)
          self.emails = value
        end
      else
        self.emails = nil
      end

      if attributes.key?(:'check_smtp')
        self.check_smtp = attributes[:'check_smtp']
      else
        self.check_smtp = false
      end

      if attributes.key?(:'include_raw_dns')
        self.include_raw_dns = attributes[:'include_raw_dns']
      else
        self.include_raw_dns = false
      end

      if attributes.key?(:'batch_size')
        self.batch_size = attributes[:'batch_size']
      else
        self.batch_size = 100
      end

      if attributes.key?(:'concurrent_requests')
        self.concurrent_requests = attributes[:'concurrent_requests']
      else
        self.concurrent_requests = 5
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @emails.nil?
        invalid_properties.push('invalid value for "emails", emails cannot be nil.')
      end

      if @emails.length > 1000
        invalid_properties.push('invalid value for "emails", number of items must be less than or equal to 1000.')
      end

      if @emails.length < 1
        invalid_properties.push('invalid value for "emails", number of items must be greater than or equal to 1.')
      end

      if !@batch_size.nil? && @batch_size > 1000
        invalid_properties.push('invalid value for "batch_size", must be smaller than or equal to 1000.')
      end

      if !@batch_size.nil? && @batch_size < 1
        invalid_properties.push('invalid value for "batch_size", must be greater than or equal to 1.')
      end

      if !@concurrent_requests.nil? && @concurrent_requests > 50
        invalid_properties.push('invalid value for "concurrent_requests", must be smaller than or equal to 50.')
      end

      if !@concurrent_requests.nil? && @concurrent_requests < 1
        invalid_properties.push('invalid value for "concurrent_requests", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @emails.nil?
      return false if @emails.length > 1000
      return false if @emails.length < 1
      return false if !@batch_size.nil? && @batch_size > 1000
      return false if !@batch_size.nil? && @batch_size < 1
      return false if !@concurrent_requests.nil? && @concurrent_requests > 50
      return false if !@concurrent_requests.nil? && @concurrent_requests < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] emails Value to be assigned
    def emails=(emails)
      if emails.nil?
        fail ArgumentError, 'emails cannot be nil'
      end

      if emails.length > 1000
        fail ArgumentError, 'invalid value for "emails", number of items must be less than or equal to 1000.'
      end

      if emails.length < 1
        fail ArgumentError, 'invalid value for "emails", number of items must be greater than or equal to 1.'
      end

      @emails = emails
    end

    # Custom attribute writer method with validation
    # @param [Object] batch_size Value to be assigned
    def batch_size=(batch_size)
      if batch_size.nil?
        fail ArgumentError, 'batch_size cannot be nil'
      end

      if batch_size > 1000
        fail ArgumentError, 'invalid value for "batch_size", must be smaller than or equal to 1000.'
      end

      if batch_size < 1
        fail ArgumentError, 'invalid value for "batch_size", must be greater than or equal to 1.'
      end

      @batch_size = batch_size
    end

    # Custom attribute writer method with validation
    # @param [Object] concurrent_requests Value to be assigned
    def concurrent_requests=(concurrent_requests)
      if concurrent_requests.nil?
        fail ArgumentError, 'concurrent_requests cannot be nil'
      end

      if concurrent_requests > 50
        fail ArgumentError, 'invalid value for "concurrent_requests", must be smaller than or equal to 50.'
      end

      if concurrent_requests < 1
        fail ArgumentError, 'invalid value for "concurrent_requests", must be greater than or equal to 1.'
      end

      @concurrent_requests = concurrent_requests
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          emails == o.emails &&
          check_smtp == o.check_smtp &&
          include_raw_dns == o.include_raw_dns &&
          batch_size == o.batch_size &&
          concurrent_requests == o.concurrent_requests
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [emails, check_smtp, include_raw_dns, batch_size, concurrent_requests].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
