=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module MailSafePro
  # Batch validation response
  class BatchEmailResponse < ApiModelBase
    # Total emails processed
    attr_accessor :count

    # Number of valid emails
    attr_accessor :valid_count

    # Number of invalid emails
    attr_accessor :invalid_count

    # Total processing time in seconds
    attr_accessor :processing_time

    # Average processing time per email
    attr_accessor :average_time

    # Individual validation results
    attr_accessor :results

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'count' => :'count',
        :'valid_count' => :'valid_count',
        :'invalid_count' => :'invalid_count',
        :'processing_time' => :'processing_time',
        :'average_time' => :'average_time',
        :'results' => :'results'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'count' => :'Integer',
        :'valid_count' => :'Integer',
        :'invalid_count' => :'Integer',
        :'processing_time' => :'Float',
        :'average_time' => :'Float',
        :'results' => :'Array<EmailResponse>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSafePro::BatchEmailResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSafePro::BatchEmailResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'count')
        self.count = attributes[:'count']
      else
        self.count = nil
      end

      if attributes.key?(:'valid_count')
        self.valid_count = attributes[:'valid_count']
      else
        self.valid_count = nil
      end

      if attributes.key?(:'invalid_count')
        self.invalid_count = attributes[:'invalid_count']
      else
        self.invalid_count = nil
      end

      if attributes.key?(:'processing_time')
        self.processing_time = attributes[:'processing_time']
      else
        self.processing_time = nil
      end

      if attributes.key?(:'average_time')
        self.average_time = attributes[:'average_time']
      else
        self.average_time = nil
      end

      if attributes.key?(:'results')
        if (value = attributes[:'results']).is_a?(Array)
          self.results = value
        end
      else
        self.results = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @count.nil?
        invalid_properties.push('invalid value for "count", count cannot be nil.')
      end

      if @count < 0
        invalid_properties.push('invalid value for "count", must be greater than or equal to 0.')
      end

      if @valid_count.nil?
        invalid_properties.push('invalid value for "valid_count", valid_count cannot be nil.')
      end

      if @valid_count < 0
        invalid_properties.push('invalid value for "valid_count", must be greater than or equal to 0.')
      end

      if @invalid_count.nil?
        invalid_properties.push('invalid value for "invalid_count", invalid_count cannot be nil.')
      end

      if @invalid_count < 0
        invalid_properties.push('invalid value for "invalid_count", must be greater than or equal to 0.')
      end

      if @processing_time.nil?
        invalid_properties.push('invalid value for "processing_time", processing_time cannot be nil.')
      end

      if @processing_time < 0.0
        invalid_properties.push('invalid value for "processing_time", must be greater than or equal to 0.0.')
      end

      if @average_time.nil?
        invalid_properties.push('invalid value for "average_time", average_time cannot be nil.')
      end

      if @average_time < 0.0
        invalid_properties.push('invalid value for "average_time", must be greater than or equal to 0.0.')
      end

      if @results.nil?
        invalid_properties.push('invalid value for "results", results cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @count.nil?
      return false if @count < 0
      return false if @valid_count.nil?
      return false if @valid_count < 0
      return false if @invalid_count.nil?
      return false if @invalid_count < 0
      return false if @processing_time.nil?
      return false if @processing_time < 0.0
      return false if @average_time.nil?
      return false if @average_time < 0.0
      return false if @results.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] count Value to be assigned
    def count=(count)
      if count.nil?
        fail ArgumentError, 'count cannot be nil'
      end

      if count < 0
        fail ArgumentError, 'invalid value for "count", must be greater than or equal to 0.'
      end

      @count = count
    end

    # Custom attribute writer method with validation
    # @param [Object] valid_count Value to be assigned
    def valid_count=(valid_count)
      if valid_count.nil?
        fail ArgumentError, 'valid_count cannot be nil'
      end

      if valid_count < 0
        fail ArgumentError, 'invalid value for "valid_count", must be greater than or equal to 0.'
      end

      @valid_count = valid_count
    end

    # Custom attribute writer method with validation
    # @param [Object] invalid_count Value to be assigned
    def invalid_count=(invalid_count)
      if invalid_count.nil?
        fail ArgumentError, 'invalid_count cannot be nil'
      end

      if invalid_count < 0
        fail ArgumentError, 'invalid value for "invalid_count", must be greater than or equal to 0.'
      end

      @invalid_count = invalid_count
    end

    # Custom attribute writer method with validation
    # @param [Object] processing_time Value to be assigned
    def processing_time=(processing_time)
      if processing_time.nil?
        fail ArgumentError, 'processing_time cannot be nil'
      end

      if processing_time < 0.0
        fail ArgumentError, 'invalid value for "processing_time", must be greater than or equal to 0.0.'
      end

      @processing_time = processing_time
    end

    # Custom attribute writer method with validation
    # @param [Object] average_time Value to be assigned
    def average_time=(average_time)
      if average_time.nil?
        fail ArgumentError, 'average_time cannot be nil'
      end

      if average_time < 0.0
        fail ArgumentError, 'invalid value for "average_time", must be greater than or equal to 0.0.'
      end

      @average_time = average_time
    end

    # Custom attribute writer method with validation
    # @param [Object] results Value to be assigned
    def results=(results)
      if results.nil?
        fail ArgumentError, 'results cannot be nil'
      end

      @results = results
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          count == o.count &&
          valid_count == o.valid_count &&
          invalid_count == o.invalid_count &&
          processing_time == o.processing_time &&
          average_time == o.average_time &&
          results == o.results
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [count, valid_count, invalid_count, processing_time, average_time, results].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
