=begin
#Email Validation API — Enterprise-grade Email Verification

#API robusta y segura para validación y verificación de correos electrónicos. Soporta verificación individual y en lote, detección de brechas, y autenticación JWT. Cumple con GDPR y dispone de planes de pago flexibles.  **🔗 Enlaces importantes:** - [Estado del sistema](https://mailsafepro.betteruptime.com) - [Documentación completa](https://email-validation-api-jlra.onrender.com/redoc)  **📧 Contacto:** mailsafepro1@gmail.com

The version of the OpenAPI document: 2.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module MailSafePro
  # API Key rotation request
  class KeyRotationRequest < ApiModelBase
    # Current API key to rotate from
    attr_accessor :old_key

    # New API key to rotate to
    attr_accessor :new_key

    # Grace period in seconds (max 30 days)
    attr_accessor :grace_period

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'old_key' => :'old_key',
        :'new_key' => :'new_key',
        :'grace_period' => :'grace_period'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'old_key' => :'String',
        :'new_key' => :'String',
        :'grace_period' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `MailSafePro::KeyRotationRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `MailSafePro::KeyRotationRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'old_key')
        self.old_key = attributes[:'old_key']
      else
        self.old_key = nil
      end

      if attributes.key?(:'new_key')
        self.new_key = attributes[:'new_key']
      else
        self.new_key = nil
      end

      if attributes.key?(:'grace_period')
        self.grace_period = attributes[:'grace_period']
      else
        self.grace_period = 86400
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @old_key.nil?
        invalid_properties.push('invalid value for "old_key", old_key cannot be nil.')
      end

      if @old_key.to_s.length > 128
        invalid_properties.push('invalid value for "old_key", the character length must be smaller than or equal to 128.')
      end

      if @old_key.to_s.length < 32
        invalid_properties.push('invalid value for "old_key", the character length must be greater than or equal to 32.')
      end

      if @new_key.nil?
        invalid_properties.push('invalid value for "new_key", new_key cannot be nil.')
      end

      if @new_key.to_s.length > 128
        invalid_properties.push('invalid value for "new_key", the character length must be smaller than or equal to 128.')
      end

      if @new_key.to_s.length < 32
        invalid_properties.push('invalid value for "new_key", the character length must be greater than or equal to 32.')
      end

      if !@grace_period.nil? && @grace_period > 2592000
        invalid_properties.push('invalid value for "grace_period", must be smaller than or equal to 2592000.')
      end

      if !@grace_period.nil? && @grace_period < 0
        invalid_properties.push('invalid value for "grace_period", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @old_key.nil?
      return false if @old_key.to_s.length > 128
      return false if @old_key.to_s.length < 32
      return false if @new_key.nil?
      return false if @new_key.to_s.length > 128
      return false if @new_key.to_s.length < 32
      return false if !@grace_period.nil? && @grace_period > 2592000
      return false if !@grace_period.nil? && @grace_period < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] old_key Value to be assigned
    def old_key=(old_key)
      if old_key.nil?
        fail ArgumentError, 'old_key cannot be nil'
      end

      if old_key.to_s.length > 128
        fail ArgumentError, 'invalid value for "old_key", the character length must be smaller than or equal to 128.'
      end

      if old_key.to_s.length < 32
        fail ArgumentError, 'invalid value for "old_key", the character length must be greater than or equal to 32.'
      end

      @old_key = old_key
    end

    # Custom attribute writer method with validation
    # @param [Object] new_key Value to be assigned
    def new_key=(new_key)
      if new_key.nil?
        fail ArgumentError, 'new_key cannot be nil'
      end

      if new_key.to_s.length > 128
        fail ArgumentError, 'invalid value for "new_key", the character length must be smaller than or equal to 128.'
      end

      if new_key.to_s.length < 32
        fail ArgumentError, 'invalid value for "new_key", the character length must be greater than or equal to 32.'
      end

      @new_key = new_key
    end

    # Custom attribute writer method with validation
    # @param [Object] grace_period Value to be assigned
    def grace_period=(grace_period)
      if grace_period.nil?
        fail ArgumentError, 'grace_period cannot be nil'
      end

      if grace_period > 2592000
        fail ArgumentError, 'invalid value for "grace_period", must be smaller than or equal to 2592000.'
      end

      if grace_period < 0
        fail ArgumentError, 'invalid value for "grace_period", must be greater than or equal to 0.'
      end

      @grace_period = grace_period
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          old_key == o.old_key &&
          new_key == o.new_key &&
          grace_period == o.grace_period
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [old_key, new_key, grace_period].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
